// This file is generated by Slice Machine. Update with care!

import BasicImage from './BasicImage';
import BigText from './BigText';
import Columns from './Columns';
import Embed from './Embed';
import FilmInfo from './FilmInfo';
import FilmItem from './FilmItem';
import Form from './Form';
import HeroFilm from './HeroFilm';
import HeroImage from './HeroImage';
import ImageSlider from './ImageSlider';
import ImageText from './ImageText';
import Partners from './Partners';
import Quote from './Quote';
import TeamItem from './TeamItem';

export {
	BasicImage,
	BigText,
	Columns,
	Embed,
	FilmInfo,
	FilmItem,
	Form,
	HeroFilm,
	HeroImage,
	ImageSlider,
	ImageText,
	Partners,
	Quote,
	TeamItem,
};

export const components = {
	basic_image: BasicImage,
	big_text: BigText,
	columns: Columns,
	embed: Embed,
	film_info: FilmInfo,
	film_item: FilmItem,
	form: Form,
	hero_film: HeroFilm,
	hero_image: HeroImage,
	image_slider: ImageSlider,
	image_text: ImageText,
	partners: Partners,
	quote: Quote,
	team_item: TeamItem,
};
