// This file is generated by Slice Machine. Update with care!

import BigText from './BigText';
import Columns from './Columns';
import HeroImage from './HeroImage';

export {
	BigText,
	Columns,
	HeroImage,
};

export const components = {
	big_text: BigText,
	columns: Columns,
	hero_image: HeroImage,
};
